site_name: CUAHSI Water Content Portal
repo_name: Water-Content-Portal
repo_url: https://github.com/abnerbog/Water-Content-Portal
edit_uri_template: 'https://cuahsi-water-portal.netlify.app/admin'

theme:
  name: "material"
  features:
    - search.suggest
    - search.highlight
    - content.action.edit
    - navigation.footer
    - toc.integrate
  icon:
    edit: material/pencil
    view: material/eye
  palette:
    - scheme: default
      toggle:
          icon: material/brightness-7
          name: Switch to dark mode
    - scheme: slate
      toggle:
          icon: material/brightness-4
          name: Switch to light mode

plugins:
  - search
  - git-revision-date-localized:
      locale: en
      type: datetime
  - mkdocs-jupyter:
      execute: true
  # - mkquartodocs

markdown_extensions:
  - tables

nav:
  - Home: index.md
  - "Field Data Collection Protocols":
    - "Surface Water Quality": 
      - "[AIMS] Surface Water Chemistry Field Sampling": Protocols/Surface-Water-Quality/AIMS_SOP_Surface_Water_Chemistry_Field_Sampling.md
    - "Ecological & Biological Monitoring": 
      - "[AIMS] Benthic Macroinvertebrate Field Sampling": Protocols/Ecological-Biological-Monitoring/AIMS_SOP_Benthic_Macroinvertebrate_Field_Sampling.md
  - "Jupyter Notebooks":
    - "Example notebooks from HydroShare": 
      - "Campus Residential Water Use Analysis": Jupyter_notebooks/CampusResidentialWaterUseAnalysis_Complete.ipynb
  # - "Quarto Docs":
  #   - "JP Gannon hydroinformatics course": 
  #     - "Intro to plotting": Quarto_docs/01-Plotting_Demo_COMPLETE.qmd
