backend:
  name: github
  branch: main
  repo: abnerbog/Water-Content-Portal
  auth_scope: repo
  open_authoring: true

public_folder: "site"
media_folder: "site/assets"
publish_mode: editorial_workflow

collections:
  - name: "protocols"
    label: "Data collection protocols"
    folder: "docs/Protocols"
    create: true
    nested:
      depth: 100 # max depth to show in the collection tree
      summary: '{{title}}' # optional summary for a tree node, defaults to the inferred title field
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}