backend:
  name: github
  branch: main
  repo: abnerbog/Water-Content-Portal
  auth_scope: repo
  open_authoring: true

public_folder: "site"
media_folder: "site/assets"
publish_mode: editorial_workflow

collections:
  - name: "ecological"
    label: "Ecological & Biological Monitoring Protocols"
    folder: "docs/Protocols/ecological-biological-monitoring"
    create: true
    slug: "{{title | slug}}"
    preview_path: "protocols/ecological-biological-monitoring/{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "water_quality"
    label: "Surface Water Quality Protocols"
    folder: "docs/Protocols/surface-water-quality"
    create: true
    slug: "{{title | slug}}"
    preview_path: "protocols/surface-water-quality/{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
