backend:
  name: github
  branch: main
  repo: abnerbog/Water-Content-Portal
  auth_scope: repo
  open_authoring: true

public_folder: "site"
media_folder: "site/assets"
publish_mode: editorial_workflow

collections:
  - name: "Ecological & Biological Monitoring Protocols"
    label: "Data Collection Protocols: Ecological & Biological Monitoring"
    folder: "docs/Protocols/Ecological & Biological Monitoring"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "Surface Water Quality Protocols"
    label: "Data Collection Protocols: Surface Water Quality"
    folder: "docs/Protocols/Surface Water Quality"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}