backend:
  name: github
  branch: main
  repo: abnerbog/Water-Content-Portal
  auth_scope: repo
  open_authoring: true

public_folder: "site"
media_folder: "site/assets"
publish_mode: editorial_workflow

collections:
  - name: "ecological"
    label: "Ecological & Biological Monitoring Protocols"
    folder: "docs/Protocols/Ecological-Biological-Monitoring"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

collections:
  - name: "water_quality"
    label: "Surface Water Quality Protocols"
    folder: "docs/Protocols/Surface-Water-Quality"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}