backend:
  name: github
  branch: main
  repo: abnerbog/Water-Content-Portal
  auth_scope: repo
  open_authoring: true

public_folder: "site"
media_folder: "site/assets"
publish_mode: editorial_workflow

collections:
  - name: "protocols"
    label: "Data Collection Protocols"
    folder: "docs/Protocols"
    create: true
    nested:
      depth: 100
      summary: "{{title}}"
    slug: "{{title | slug}}"
    preview_path: "protocols/{{nested.slug}}/{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
